
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SOFFIAH AI NURJANAH
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import koneksi.koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JTable;


public class PenjualanTiket extends javax.swing.JFrame {
    public Connection con=new koneksi().getKoneksi();
    DefaultTableModel tabmodel = null;
    PreparedStatement pstat= null;
    public Statement stat;
    public ResultSet rs;
    
    
    String sql;
    int tiket;
    int harga;
    int total;
    private int ekonomi;
    private int bisnis;
    
   
    
    
    /**
     * Creates new form PenjualanTiket
     */
    public PenjualanTiket() {
        initComponents();
       
        
    }
    
    public void tampildata(){
      try{
        Connection con = koneksi.getKoneksi();
        Statement stat = con.createStatement();
        ResultSet rs = stat.executeQuery("SELECT * from penjualan");
        DefaultTableModel model = (DefaultTableModel) tb_penjualan.getModel();
        tabmodel.setRowCount(0);
        
        while(rs.next()){
            String No_Pemesanan = rs.getString("No_Pemesanan");
            String Nama = rs.getString("Nama");
            String Kode_Kereta = rs.getString("Kode_Kereta");
            String Jenis_Kereta = rs.getString("Jenis_Kereta");
            String Jurusan = rs.getString("Jurusan");
            String Jumlah_Tiket = rs.getString("Jumlah_Tiket");
            String Harga = rs.getString("Harga");
            String Total_Bayar = rs.getString("Total_Bayar");
            model.addRow(new Object[]{No_Pemesanan,Nama,Kode_Kereta,Jenis_Kereta,Jurusan,Jumlah_Tiket,Harga,Total_Bayar});
        }
        
        }catch(SQLException e){
         System.out.println(e.getMessage());
          JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat terhubung ke database");
        }
    }
    
    public Boolean tidak_kosong(){
        return (txt_no.getText().equals("") || txt_nama.getText().equals("") || cmbkode.getSelectedItem().equals("") || cmbjenis.getSelectedItem().equals("") || txtharga.getText().equals("") || cb_jurusan.getSelectedItem().equals("") || txt_jml.getText().equals("") || txt_total.getText().equals(""));
    }
   



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_no = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_jml = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        btn_beli = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        cb_jurusan = new javax.swing.JComboBox<>();
        cmbkode = new javax.swing.JComboBox<>();
        cmbjenis = new javax.swing.JComboBox<>();
        btnhitung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_penjualan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PENJUALAN TIKET KERETA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("No Pesanan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kode Kereta");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kereta");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jurusan");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jumlah Tiket");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Harga");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Total Bayar");

        txt_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noActionPerformed(evt);
            }
        });

        txt_jml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jmlActionPerformed(evt);
            }
        });
        txt_jml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jmlKeyReleased(evt);
            }
        });

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        txtharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthargaKeyReleased(evt);
            }
        });

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        btn_beli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_beli.setText("Beli");
        btn_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_beliActionPerformed(evt);
            }
        });

        btn_ubah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_batal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_batal.setText("X");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_keluar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        cb_jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Jakarta-Bandung", "Jakarta-Yogyakarta", "Bandung-Surabaya", "Bekasi-Jakarta Kota", "Bekasi-Pasar Senen" }));
        cb_jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_jurusanActionPerformed(evt);
            }
        });

        cmbkode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih -", "KRL001", "KRL002", "KRL003", "KRL004", "KRL005" }));
        cmbkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkodeActionPerformed(evt);
            }
        });

        cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih -", "Ekonomi", "Bisnis" }));
        cmbjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjenisActionPerformed(evt);
            }
        });

        btnhitung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        tb_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Pemesanan", "Nama", "Kode Kereta", "Jenis Kereta", "Jurusan", "Jumlah Tiket", "Harga", "Total Bayar"
            }
        ));
        jScrollPane1.setViewportView(tb_penjualan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_batal)
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbjenis, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbkode, javax.swing.GroupLayout.Alignment.LEADING, 0, 78, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(218, 218, 218)
                                        .addComponent(btnhitung)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addGap(46, 46, 46))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addGap(18, 18, 18))))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cb_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(148, 148, 148))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(39, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btn_beli)
                .addGap(52, 52, 52)
                .addComponent(btn_ubah)
                .addGap(51, 51, 51)
                .addComponent(btn_delete)
                .addGap(53, 53, 53)
                .addComponent(btn_keluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cb_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_jml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(btnhitung))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_beli)
                    .addComponent(btn_ubah)
                    .addComponent(btn_delete)
                    .addComponent(btn_keluar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_beliActionPerformed
        // TODO add your handling code here:
         try{
            String sql= "INSERT INTO penjualan VALUES('" + txt_no.getText()
                     + "','"+txt_nama.getText()
                     + "','"+cmbkode.getSelectedItem()
                     + "','"+cmbjenis.getSelectedItem()
                     + "','"+cb_jurusan.getSelectedItem()
                     + "','"+txt_jml.getText()
                     + "','"+txtharga.getText()
                     + "','"+txt_total.getText()+ "')";
             java.sql.Connection con= koneksi.getKoneksi();
             java.sql.PreparedStatement pstat= con.prepareStatement(sql);
             pstat.execute();
             tampildata();
             JOptionPane.showMessageDialog(null, "Pembelian Tiket Berhasil");
         }catch(SQLException e){
             JOptionPane.showMessageDialog(null, "Pembelian Tiket Gagal");
         }
         
    }//GEN-LAST:event_btn_beliActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        if(tidak_kosong()){
            try{
                stat= con.createStatement();
                String sql= "UPDATE penjualan SET No_Pemesanan='"+txt_no.getText() +"', Nama='"+txt_nama.getText() +"', Kode_Kereta='"+cmbkode.getSelectedItem() +"', Jenis_Kereta='"+cmbjenis.getSelectedItem() +"', Jurusan='"+cb_jurusan.getSelectedItem() +"', Jumlah_Tiket='"+txt_jml.getText() +"', Harga='"+txtharga.getText() +"', Total_Bayar='"+txt_total.getText() +"'";
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Berhasil Diubah");
                tampildata();
            } catch(SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int answer= JOptionPane.showConfirmDialog(null, "Anda Yakin Akan Keluar ?", "Keluar", JOptionPane.OK_OPTION);
        if (answer==JOptionPane.OK_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
       dispose();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        F_Login batal= new F_Login();
        batal.setVisible(true);
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_jmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jmlActionPerformed
        // TODO add your handling code here:
        tiket=Integer.parseInt(txt_jml.getText());
        harga=Integer.parseInt(txtharga.getText());
        total=tiket*harga;
        txt_total.setText(String.valueOf(total));
    }//GEN-LAST:event_txt_jmlActionPerformed

    private void txt_jmlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jmlKeyReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txt_jmlKeyReleased

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
        harga=Integer.parseInt(txtharga.getText());
        tiket=Integer.parseInt(txt_jml.getText());
        total=harga*tiket;
        txt_total.setText(String.valueOf(total));
    }//GEN-LAST:event_txthargaActionPerformed

    private void txthargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a=Integer.valueOf(txtharga.getText());
        b=Integer.valueOf(txt_jml.getText());
        c=a*b;
        txt_total.setText(""+c);
    }//GEN-LAST:event_txthargaKeyReleased

    private void cb_jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_jurusanActionPerformed
        // TODO add your handling code here:
        if(cb_jurusan.getSelectedItem().equals("Pilih")){
            txtharga.setText("");
        }else if(cb_jurusan.getSelectedItem().equals("Jakarta-Bandung")){
            ekonomi=100000;
            bisnis=300000;
        }else if(cb_jurusan.getSelectedItem().equals("Jakarta-Yogyakarta")){
            ekonomi=150000;
            bisnis=300000;
        }else if(cb_jurusan.getSelectedItem().equals("Bandung-Surabaya")){
            ekonomi=200000;
            bisnis=350000;
        }else if(cb_jurusan.getSelectedItem().equals("Bekasi-Jakarta Kota")){
            ekonomi=75000;
            bisnis=150000;
        }else if(cb_jurusan.getSelectedItem().equals("Bekasi-Pasar Senen")){
            ekonomi=75000;
            bisnis=120000;
        }
            
    }//GEN-LAST:event_cb_jurusanActionPerformed

    private void cmbkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkodeActionPerformed

    }//GEN-LAST:event_cmbkodeActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noActionPerformed

    private void cmbjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjenisActionPerformed
        if (cmbjenis.getSelectedItem().equals("Pilih")){
            txtharga.setText("");
            cb_jurusan.getSelectedItem();
        }
    }//GEN-LAST:event_cmbjenisActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        int a = Integer.parseInt(txtharga.getText());
        int b = Integer.parseInt(txt_jml.getText());
        int hasil = a*b;
        txt_total.setText(Integer.toString(hasil));
    }//GEN-LAST:event_btnhitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenjualanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenjualanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenjualanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenjualanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenjualanTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_beli;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JButton btnhitung;
    private javax.swing.JComboBox<String> cb_jurusan;
    private javax.swing.JComboBox<String> cmbjenis;
    private javax.swing.JComboBox<String> cmbkode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_penjualan;
    private javax.swing.JTextField txt_jml;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_no;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txtharga;
    // End of variables declaration//GEN-END:variables

}
